apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: build
spec:
  serviceAccountName: knative-build
  source:
    git:
      url: https://github.com/larchanjo/talk-tdc-2019-knative
      revision: master
    subPath: "code/"
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.1.0
    args:
    - --dockerfile=/workspace/Dockerfile
    - --destination=gcr.io/MY_GCP_PROJECT/tdc:v1